# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build, Test, and Deploy ASP.Net Core app to Azure Web App - thamco

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Restore dependencies
        run: dotnet restore

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test --configuration Release --logger "trx;LogFileName=testresults.trx"

      - name: Publish test artifacts
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/tests

      - name: Upload test artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ${{env.DOTNET_ROOT}}/tests

  deploy:
    runs-on: windows-latest
    needs: build-and-test
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download app artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Download test artifact from build-and-test job
        uses: actions/download-artifact@v2
        with:
          name: test-results

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'thamco'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4CECDC469E8240FCA7D0F046672CA053 }}
          package: .

      - name: Publish test results
        uses: mike-ward/publish-test-results-action@v2
        with:
          test-results-file: '**/testresults.trx'
